### ISSUE TITLE
Bugfix for compiling python interface

### ISSUE THREAD

**Issue by svigerske** [coin-or/qpOASES#52]
Issue created by migration from Trac.

Original creator: ferreau

Original creation time: 2016-07-08 13:13:37

Assignee: ferreau

Version: 3.2.0

`make python` does not work in qpOASES 3.2.0 (as well as in the svn repository). It leads to the following error:

```
qpoases.cpp:12247:271: error: cannot convert ‘qpOASES::real_t {aka
double}’ to ‘qpOASES::returnValue’ for argument ‘1’ to ‘PyObject*
__Pyx_PyInt_From_enum__qpOASES_3a__3a_returnValue(qpOASES::returnValue)’
```

The bug comes from `qpoases.pxd`, where lines 447-449 need to be updated to:

```
real_t getKktViolation(const QProblem*,  const real_t*, const real_t*, const real_t*)
real_t getKktViolation(const QProblemB*, const real_t*, const real_t*, const real_t*)
real_t getKktViolation(const SQProblem*, const real_t*, const real_t*, const real_t*)
```

The return type is wrong in the distribution.

(note: reported on behalf of another user)

**Comment by svigerske** [comment]
Comment by ferreau created at 2016-08-12 13:01:17

fixed in `trunk` in revision 202

**Comment by svigerske** [comment]
Comment by ferreau created at 2016-08-12 13:01:17

Changing status from new to assigned.

**Comment by svigerske** [comment]
Comment by ferreau created at 2016-08-12 13:01:33

Resolution: fixed
